# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a31bdceedd9fccd71d857214cded3045bd47a7f21c8b6b5e47fa6a6c2b404761a7694f5de08777efb97923fec60facc022642a1f809e86e6b1ac3c21005dee

test:
  secret_key_base: 8c8f4e6f537bd07f885571b4d6cdbdd8bb4ee1c1fa1503ef3f0f291d9722b60734d6d91043f991a6366186244b330d7c279bca641b62df8f79bd3086bf50cf92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
